const allProducts = [
    {
      id: 1,
      name: "Gold Necklace",
      image: "https://cdn.caratlane.com/media/catalog/product/J/R/JR08213-PTP600_3_lar.jpg",
      price: 50000,
      status: "Live",
      category: "Necklaces",
      sellerName: "Joyalukkas",
      weight: "50g",
      stockQuantity: 10,
      lastUpdated: "2023-09-15",
      sellerAddress: "123 Gold Street",
      city: "Mumbai",
      appraiser: "John Doe",
      photographer: "Jane Smith",
    },
    {
      id: 2,
      name: "Diamond Earrings",
      image: "https://cdn.caratlane.com/media/catalog/product/J/T/JT02485-1YP900_1_lar.jpg",
      price: 80000,
      status: "Pending",
      category: "Earrings",
      sellerName: "Tanishq",
      weight: "20g",
      stockQuantity: 5,
      lastUpdated: "2023-09-10",
      sellerAddress: "456 Silver Avenue",
      city: "Delhi",
      appraiser: "Alice Brown",
      photographer: "Bob Johnson",
    },
    {
      id: 2,
      name: "Diamond Earrings",
      image: "https://cdn.caratlane.com/media/catalog/product/J/T/JT02485-1YP900_1_lar.jpg",
      price: 80000,
      status: "Pending",
      category: "Earrings",
      sellerName: "Tanishq",
      weight: "20g",
      stockQuantity: 5,
      lastUpdated: "2023-09-10",
      sellerAddress: "456 Silver Avenue",
      city: "Delhi",
      appraiser: "Alice Brown",
      photographer: "Bob Johnson",
    },
    {
      id: 2,
      name: "Diamond Earrings",
      image: "https://cdn.caratlane.com/media/catalog/product/J/T/JT02485-1YP900_1_lar.jpg",
      price: 80000,
      status: "Pending",
      category: "Earrings",
      sellerName: "Tanishq",
      weight: "20g",
      stockQuantity: 5,
      lastUpdated: "2023-09-10",
      sellerAddress: "456 Silver Avenue",
      city: "Delhi",
      appraiser: "Alice Brown",
      photographer: "Bob Johnson",
    },
    {
      id: 2,
      name: "Diamond Earrings",
      image: "https://cdn.caratlane.com/media/catalog/product/J/T/JT02485-1YP900_1_lar.jpg",
      price: 80000,
      status: "Pending",
      category: "Earrings",
      sellerName: "Tanishq",
      weight: "20g",
      stockQuantity: 5,
      lastUpdated: "2023-09-10",
      sellerAddress: "456 Silver Avenue",
      city: "Delhi",
      appraiser: "Alice Brown",
      photographer: "Bob Johnson",
    },
    // Add more products as needed
  ];
  
  export default allProducts;
  